spring:
  application:
    name: urbannest
  profiles:
    active: local
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /api

firebase:
  service-account-file: firebase-service-account.json

aws:
  s3:
    access-key-id: ${AWS_S3_ACCESS_KEY_ID}
    access-key-secret: ${AWS_S3_ACCESS_KEY_SECRET}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION}