spring:
  application:
    name: urbannest
  profiles:
    active: local
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /api

firebase:
  service-account-file: classpath:firebase-service-account.json

aws:
  s3:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    access-key-secret: ${AWS_ACCESS_KEY_SECRET}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}

encryption:
  nid-key: ${ENCRYPTION_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics

  prometheus:
    metrics:
      export:
        enabled: true